//
// Created by Alex Chi on 2019-07-10.
//

#ifndef RISCV_SIMULATOR_OOOCOMMON_H
#define RISCV_SIMULATOR_OOOCOMMON_H

enum RSID {
    NONE = 0,
    RS_BEGIN = 255,
    ADD1, ADD2, ADD3, LOAD1, STORE1, BRANCH1,
    RS_END
};

#endif //RISCV_SIMULATOR_OOOCOMMON_H
